#!/usr/bin/env bats

load helper

setup() {
  load_entrypoint

  INSTANCES_DIR="${ARK_TOOLS_DIR}/instances"
  GAME_CLIENT_PORT=7778
  SERVER_LIST_PORT=27015
  RCON_PORT=32330
  SUB_KEYS=(ragnarok aberration)
}

@test "writes one config per key" {
  remake_sub_instances_cfg

  [ -f "${INSTANCES_DIR}/sub.ragnarok.cfg" ]
  [ -f "${INSTANCES_DIR}/sub.aberration.cfg" ]
}

@test "marks generated configs as auto-regenerated" {
  remake_sub_instances_cfg

  run head -n1 "${INSTANCES_DIR}/sub.ragnarok.cfg"

  assert_contains "$output" "Auto-regenerated"
}

@test "fills the key into map, save dir and variable names" {
  remake_sub_instances_cfg

  run cat "${INSTANCES_DIR}/sub.ragnarok.cfg"

  assert_contains "$output" 'serverMap="${SUB_ragnarok_SERVER_MAP:-ragnarok}"'
  assert_contains "$output" 'ark_AltSaveDirectoryName="${SUB_ragnarok_SAVE_DIR:-sub.ragnarok}"'
  assert_not_contains "$output" "<KEY>"
}

@test "offsets the ports of the first sub instance" {
  remake_sub_instances_cfg

  run cat "${INSTANCES_DIR}/sub.ragnarok.cfg"

  assert_contains "$output" 'ark_Port=${SUB_ragnarok_GAME_CLIENT_PORT:-7780}'
  assert_contains "$output" 'ark_QueryPort=${SUB_ragnarok_SERVER_LIST_PORT:-27016}'
  assert_contains "$output" 'ark_RCONPort=${SUB_ragnarok_RCON_PORT:-32331}'
}

@test "offsets the ports of the second sub instance further" {
  remake_sub_instances_cfg

  run cat "${INSTANCES_DIR}/sub.aberration.cfg"

  assert_contains "$output" 'ark_Port=${SUB_aberration_GAME_CLIENT_PORT:-7782}'
  assert_contains "$output" 'ark_QueryPort=${SUB_aberration_SERVER_LIST_PORT:-27017}'
  assert_contains "$output" 'ark_RCONPort=${SUB_aberration_RCON_PORT:-32332}'
}

@test "leaves the game client port of the main instance free" {
  remake_sub_instances_cfg

  run cat "${INSTANCES_DIR}/sub.ragnarok.cfg"

  assert_not_contains "$output" ":-7778}"
  assert_not_contains "$output" ":-7779}"
}

@test "numbers the session names after the main instance" {
  remake_sub_instances_cfg

  run cat "${INSTANCES_DIR}/sub.ragnarok.cfg"
  assert_contains "$output" '${SESSION_NAME}2'

  run cat "${INSTANCES_DIR}/sub.aberration.cfg"
  assert_contains "$output" '${SESSION_NAME}3'
}

@test "drops the config of a key that is gone" {
  remake_sub_instances_cfg

  SUB_KEYS=(ragnarok)
  remake_sub_instances_cfg

  [ -f "${INSTANCES_DIR}/sub.ragnarok.cfg" ]
  [ ! -e "${INSTANCES_DIR}/sub.aberration.cfg" ]
}

@test "drops every generated config once the keys are gone" {
  remake_sub_instances_cfg

  SUB_KEYS=()
  remake_sub_instances_cfg

  run find "${INSTANCES_DIR}" -name 'sub.*.cfg'
  [ -z "$output" ]
}

@test "refuses to overwrite a config it did not generate" {
  echo "# my own sub instance" > "${INSTANCES_DIR}/sub.ragnarok.cfg"

  run remake_sub_instances_cfg

  [ "$status" -eq 1 ]
  assert_contains "$output" "was not generated by this image"
  assert_contains "$output" "drop 'ragnarok' from SUB_INSTANCE_KEYS"
}

@test "leaves a config it did not generate untouched" {
  echo "# my own sub instance" > "${INSTANCES_DIR}/sub.ragnarok.cfg"

  run remake_sub_instances_cfg

  run cat "${INSTANCES_DIR}/sub.ragnarok.cfg"
  [ "$output" = "# my own sub instance" ]
}

@test "ignores unrelated files in the instances directory" {
  echo "# main" > "${INSTANCES_DIR}/main.cfg"

  remake_sub_instances_cfg

  run cat "${INSTANCES_DIR}/main.cfg"
  [ "$output" = "# main" ]
}

@test "generates configs without calling arkmanager or steamcmd" {
  remake_sub_instances_cfg

  assert_stubs_installed_and_unused
}
